--- title: "Github" date: 2021-03-31 ---
author: Morgan Navarrete
email: your-email@domain.com
description: > This is my page

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true
theme: minima

