title: Morgans Github Page
author: Morgan Navarrete
email: mnava919@evit.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first attempt at a github page.
  
  ---
title: "Morgans Github Page"
date: 2019-01-20
---
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
